quarkus.http.port=8080
quarkus.application.name=api-gateway

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000,http://localhost:5173
quarkus.http.cors.headers=Authorization,Content-Type,Accept,Cache-Control,Last-Event-ID,X-User-Id
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS

quarkus.oidc.auth-server-url=http://localhost:8180/realms/sportify
quarkus.oidc.client-id=api-gateway
quarkus.oidc.application-type=service

quarkus.rest-client.auth-service.url=http://localhost:8081
quarkus.rest-client.auth-service.scope=jakarta.inject.Singleton

quarkus.rest-client.field-service.url=http://localhost:8082
quarkus.rest-client.field-service.scope=jakarta.inject.Singleton

quarkus.rest-client.booking-service.url=http://localhost:8083
quarkus.rest-client.booking-service.scope=jakarta.inject.Singleton

quarkus.rest-client.payment-service.url=http://localhost:8084
quarkus.rest-client.payment-service.scope=jakarta.inject.Singleton

quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n
quarkus.log.level=INFO
quarkus.log.category."com.sportify".level=DEBUG

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Sportify API Gateway
quarkus.smallrye-openapi.info-version=1.0.0

%dev.quarkus.oidc.auth-server-url=http://localhost:8180/realms/sportify
%dev.quarkus.oidc.enabled=false
