quarkus.http.port=8084
quarkus.application.name=payment-service

# CORS — cho phép frontend gọi SSE endpoints trực tiếp
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000,http://localhost:5173
quarkus.http.cors.headers=Authorization,Content-Type,Accept,Cache-Control,X-User-Id
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/payment_db
quarkus.datasource.username=root
quarkus.datasource.password=123456

quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=false

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

quarkus.oidc.auth-server-url=http://localhost:8180/realms/sportify
quarkus.oidc.client-id=payment-service
quarkus.oidc.credentials.secret=LAauNEuVWnydm4BYng1EbtucZJnyexYH
quarkus.oidc.application-type=service

quarkus.oidc.roles.role-claim-path=realm_access/roles

booking-service/mp-rest/url=http://localhost:8083
booking-service/mp-rest/scope=jakarta.inject.Singleton

vnpay.tmn-code=A1RIX4JB
vnpay.hash-secret=SHMQNWLNPGLYBNWGZGZETBSBPSYPAZGS
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8084/api/v1/payments/vnpay/callback

payment.frontend-return-url=http://localhost:5173/payment/vnpay-return

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Payment Service API
quarkus.smallrye-openapi.info-version=1.0.0

%dev.quarkus.hibernate-orm.database.generation=none
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.flyway.clean-at-start=true
%dev.quarkus.oidc.enabled=false
%dev.booking-service/mp-rest/url=http://localhost:8083
