quarkus.http.port=8084
quarkus.application.name=payment-service

quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/payment_db
quarkus.datasource.username=root
quarkus.datasource.password=123456

quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=false

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

quarkus.oidc.auth-server-url=http://localhost:8180/realms/sportify
quarkus.oidc.client-id=payment-service
quarkus.oidc.application-type=service

booking-service/mp-rest/url=http://localhost:8083
booking-service/mp-rest/scope=jakarta.inject.Singleton

vnpay.tmn-code=ZKTAL3T1
vnpay.hash-secret=GPYEKL2WXS5HMXGKNCETX7713DUQ86E7
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8084/api/v1/payments/vnpay/callback

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Payment Service API
quarkus.smallrye-openapi.info-version=1.0.0

%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.oidc.enabled=false
%dev.booking-service/mp-rest/url=http://localhost:8083
